version: "3.8"

services:
  form-helper:
    image: form-helper
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      target: form-helper
    command: ["streamlit","run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    volumes:
      - ./:/app/
      - /app/.venv
      - /app/__pycache__
    ports:
      - 8501:8501
